[package]
name = "codyssi"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
perf = "warn"
complexity = "warn"
correctness = "warn"
style = "warn"
